// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     android.net.connectivity.org.chromium.base.BaseFeatureMap

#ifndef android_net_connectivity_org_chromium_base_BaseFeatureMap_JNI
#define android_net_connectivity_org_chromium_base_BaseFeatureMap_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_internal.h"
namespace base::android {

// Java to native functions
// Forward declaration. To be implemented by the including .cc file.
static jlong JNI_BaseFeatureMap_GetNativeMap(JNIEnv* env);

JNI_ZERO_BOUNDARY_EXPORT jlong Java_android_net_connectivity_J_N_M4CBnF70(
    JNIEnv* env,
    jclass jcaller) {
  auto _ret = JNI_BaseFeatureMap_GetNativeMap(env);
  return _ret;
}



}  // namespace base::android

#endif  // android_net_connectivity_org_chromium_base_BaseFeatureMap_JNI
