// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     android.net.connectivity.org.chromium.base.BuildInfo

#ifndef android_net_connectivity_org_chromium_base_BuildInfo_JNI
#define android_net_connectivity_org_chromium_base_BuildInfo_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_internal.h"

// Class Accessors
#ifndef android_net_connectivity_org_chromium_base_BuildInfo_clazz_defined
#define android_net_connectivity_org_chromium_base_BuildInfo_clazz_defined
inline jclass android_net_connectivity_org_chromium_base_BuildInfo_clazz(JNIEnv* env) {
  static const char kClassName[] = "android.net.connectivity.org.chromium.base.BuildInfo";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


// Native to Java functions
static jni_zero::ScopedJavaLocalRef<jobjectArray> Java_BuildInfo_getAll(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_net_connectivity_org_chromium_base_BuildInfo_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getAll",
      "()[Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  jobjectArray _ret2 = static_cast<jobjectArray>(_ret);
  return jni_zero::ScopedJavaLocalRef<jobjectArray>(env, _ret2);
}

static jni_zero::ScopedJavaLocalRef<jstring> Java_BuildInfo_lazyGetHostSigningCertSha256(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_net_connectivity_org_chromium_base_BuildInfo_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "lazyGetHostSigningCertSha256",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

static void Java_BuildInfo_setGmsVersionCodeForTest(
    JNIEnv* env,
    std::string const& gmsVersionCode) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_net_connectivity_org_chromium_base_BuildInfo_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "setGmsVersionCodeForTest",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  jni_zero::ScopedJavaLocalRef<jobject> converted_gmsVersionCode = jni_zero::ToJniType(
      env,
      gmsVersionCode);
  env->CallStaticVoidMethod(clazz, call_context.method_id(), converted_gmsVersionCode.obj());
}



#endif  // android_net_connectivity_org_chromium_base_BuildInfo_JNI
