// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     android.net.connectivity.org.chromium.base.BundleUtils

#ifndef android_net_connectivity_org_chromium_base_BundleUtils_JNI
#define android_net_connectivity_org_chromium_base_BundleUtils_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_internal.h"

// Class Accessors
#ifndef android_net_connectivity_org_chromium_base_BundleUtils_clazz_defined
#define android_net_connectivity_org_chromium_base_BundleUtils_clazz_defined
inline jclass android_net_connectivity_org_chromium_base_BundleUtils_clazz(JNIEnv* env) {
  static const char kClassName[] = "android.net.connectivity.org.chromium.base.BundleUtils";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


// Native to Java functions
static jni_zero::ScopedJavaLocalRef<jstring> Java_BundleUtils_getNativeLibraryPath(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& libraryName,
    const jni_zero::JavaRef<jstring>& splitName) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_net_connectivity_org_chromium_base_BundleUtils_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getNativeLibraryPath",
      "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      libraryName.obj(),
      splitName.obj());
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

static jboolean Java_BundleUtils_isBundleForNative(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_net_connectivity_org_chromium_base_BundleUtils_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isBundleForNative",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id());
  return _ret;
}



#endif  // android_net_connectivity_org_chromium_base_BundleUtils_JNI
