// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     android.net.connectivity.org.chromium.base.FeatureList

#ifndef android_net_connectivity_org_chromium_base_FeatureList_JNI
#define android_net_connectivity_org_chromium_base_FeatureList_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_internal.h"
namespace base::android {

// Java to native functions
// Forward declaration. To be implemented by the including .cc file.
static jboolean JNI_FeatureList_IsInitialized(JNIEnv* env);

JNI_ZERO_BOUNDARY_EXPORT jboolean Java_android_net_connectivity_J_N_M8oCuMGH(
    JNIEnv* env,
    jclass jcaller) {
  auto _ret = JNI_FeatureList_IsInitialized(env);
  return _ret;
}



}  // namespace base::android

#endif  // android_net_connectivity_org_chromium_base_FeatureList_JNI
