/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.ondevicepersonalization;

import android.annotation.NonNull;
import android.annotation.Nullable;
import android.os.Parcelable;

import com.android.ondevicepersonalization.internal.util.AnnotationValidations;
import com.android.ondevicepersonalization.internal.util.DataClass;

import java.util.List;

/**
 * The result for one of the slots in the request from a calling app.
 *
 * @hide
 */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public final class SlotResult implements Parcelable {
    /**
     * An identifier for this slot. Will be logged in the queries table and
     * available for reporting. Must be a key in REMOTE_DATA.
     */
    @NonNull private String mSlotKey = "";

    /**
     * A list of keys in the REMOTE_DATA table that represent bids to be rendered
     * in this slot.
     */
    @Nullable private List<String> mRenderedBidKeys = null;
    /**
     * A list of bids with metrics to be logged in the QUERIES table.
     */
    @Nullable private List<Bid> mLoggedBids = null;



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/SlotResult.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    /* package-private */ SlotResult(
            @NonNull String slotKey,
            @Nullable List<String> renderedBidKeys,
            @Nullable List<Bid> loggedBids) {
        this.mSlotKey = slotKey;
        AnnotationValidations.validate(
                NonNull.class, null, mSlotKey);
        this.mRenderedBidKeys = renderedBidKeys;
        this.mLoggedBids = loggedBids;

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * An identifier for this slot. Will be logged in the queries table and
     * available for reporting. Must be a key in REMOTE_DATA.
     */
    @DataClass.Generated.Member
    public @NonNull String getSlotKey() {
        return mSlotKey;
    }

    /**
     * A list of keys in the REMOTE_DATA table that represent bids to be rendered
     * in this slot.
     */
    @DataClass.Generated.Member
    public @Nullable List<String> getRenderedBidKeys() {
        return mRenderedBidKeys;
    }

    /**
     * A list of bids with metrics to be logged in the QUERIES table.
     */
    @DataClass.Generated.Member
    public @Nullable List<Bid> getLoggedBids() {
        return mLoggedBids;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(SlotResult other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        SlotResult that = (SlotResult) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mSlotKey, that.mSlotKey)
                && java.util.Objects.equals(mRenderedBidKeys, that.mRenderedBidKeys)
                && java.util.Objects.equals(mLoggedBids, that.mLoggedBids);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mSlotKey);
        _hash = 31 * _hash + java.util.Objects.hashCode(mRenderedBidKeys);
        _hash = 31 * _hash + java.util.Objects.hashCode(mLoggedBids);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (mRenderedBidKeys != null) flg |= 0x2;
        if (mLoggedBids != null) flg |= 0x4;
        dest.writeByte(flg);
        dest.writeString(mSlotKey);
        if (mRenderedBidKeys != null) dest.writeStringList(mRenderedBidKeys);
        if (mLoggedBids != null) dest.writeParcelableList(mLoggedBids, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ SlotResult(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        String slotKey = in.readString();
        List<String> renderedBidKeys = null;
        if ((flg & 0x2) != 0) {
            renderedBidKeys = new java.util.ArrayList<>();
            in.readStringList(renderedBidKeys);
        }
        List<Bid> loggedBids = null;
        if ((flg & 0x4) != 0) {
            loggedBids = new java.util.ArrayList<>();
            in.readParcelableList(loggedBids, Bid.class.getClassLoader());
        }

        this.mSlotKey = slotKey;
        AnnotationValidations.validate(
                NonNull.class, null, mSlotKey);
        this.mRenderedBidKeys = renderedBidKeys;
        this.mLoggedBids = loggedBids;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<SlotResult> CREATOR
            = new Parcelable.Creator<SlotResult>() {
        @Override
        public SlotResult[] newArray(int size) {
            return new SlotResult[size];
        }

        @Override
        public SlotResult createFromParcel(@NonNull android.os.Parcel in) {
            return new SlotResult(in);
        }
    };

    /**
     * A builder for {@link SlotResult}
     */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static final class Builder {

        private @NonNull String mSlotKey;
        private @Nullable List<String> mRenderedBidKeys;
        private @Nullable List<Bid> mLoggedBids;

        private long mBuilderFieldsSet = 0L;

        public Builder() {
        }

        /**
         * An identifier for this slot. Will be logged in the queries table and
         * available for reporting. Must be a key in REMOTE_DATA.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setSlotKey(@NonNull String value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mSlotKey = value;
            return this;
        }

        /**
         * A list of keys in the REMOTE_DATA table that represent bids to be rendered
         * in this slot.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setRenderedBidKeys(@NonNull List<String> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mRenderedBidKeys = value;
            return this;
        }

        /** @see #setRenderedBidKeys */
        @DataClass.Generated.Member
        public @NonNull Builder addRenderedBidKeys(@NonNull String value) {
            // You can refine this method's name by providing item's singular name, e.g.:
            // @DataClass.PluralOf("item")) mItems = ...

            if (mRenderedBidKeys == null) setRenderedBidKeys(new java.util.ArrayList<>());
            mRenderedBidKeys.add(value);
            return this;
        }

        /**
         * A list of bids with metrics to be logged in the QUERIES table.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setLoggedBids(@NonNull List<Bid> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4;
            mLoggedBids = value;
            return this;
        }

        /** @see #setLoggedBids */
        @DataClass.Generated.Member
        public @NonNull Builder addLoggedBids(@NonNull Bid value) {
            // You can refine this method's name by providing item's singular name, e.g.:
            // @DataClass.PluralOf("item")) mItems = ...

            if (mLoggedBids == null) setLoggedBids(new java.util.ArrayList<>());
            mLoggedBids.add(value);
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @NonNull SlotResult build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x8; // Mark builder used

            if ((mBuilderFieldsSet & 0x1) == 0) {
                mSlotKey = "";
            }
            if ((mBuilderFieldsSet & 0x2) == 0) {
                mRenderedBidKeys = null;
            }
            if ((mBuilderFieldsSet & 0x4) == 0) {
                mLoggedBids = null;
            }
            SlotResult o = new SlotResult(
                    mSlotKey,
                    mRenderedBidKeys,
                    mLoggedBids);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x8) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1681847760091L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/SlotResult.java",
            inputSignatures = "private @android.annotation.NonNull java.lang.String mSlotKey\nprivate @android.annotation.Nullable java.util.List<java.lang.String> mRenderedBidKeys\nprivate @android.annotation.Nullable java.util.List<android.ondevicepersonalization.Bid> mLoggedBids\nclass SlotResult extends java.lang.Object implements [android.os.Parcelable]\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
