// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     android.net.connectivity.org.chromium.net.GURLUtils

#ifndef android_net_connectivity_org_chromium_net_GURLUtils_JNI
#define android_net_connectivity_org_chromium_net_GURLUtils_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_internal.h"
namespace net {

// Java to native functions
// Forward declaration. To be implemented by the including .cc file.
static jni_zero::ScopedJavaLocalRef<jstring> JNI_GURLUtils_GetOrigin(
    JNIEnv* env,
    const jni_zero::JavaParamRef<jstring>& url);

JNI_ZERO_BOUNDARY_EXPORT jobject Java_android_net_connectivity_J_N_MMZmegZ6(
    JNIEnv* env,
    jclass jcaller,
    jobject url) {
  auto _ret = JNI_GURLUtils_GetOrigin(
      env,
      jni_zero::JavaParamRef<jstring>(env, static_cast<jstring>(url)));
  return _ret.ReleaseLocal();
}



}  // namespace net

#endif  // android_net_connectivity_org_chromium_net_GURLUtils_JNI
