// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


// This file is autogenerated by
//     third_party/jni_zero/jni_generator.py
// For
//     android/net/connectivity/org/chromium/net/HttpUtil

#ifndef android_net_connectivity_org_chromium_net_HttpUtil_JNI
#define android_net_connectivity_org_chromium_net_HttpUtil_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_helper.h"


// Step 1: Forward declarations.


// Step 2: Constants (optional).


// Step 3: Method stubs.
namespace net {

static jboolean JNI_HttpUtil_IsAllowedHeader(JNIEnv* env, const
    base::android::JavaParamRef<jstring>& headerName,
    const base::android::JavaParamRef<jstring>& headerValue);

JNI_BOUNDARY_EXPORT jboolean Java_android_net_connectivity_J_N_M5ID1qiR(
    JNIEnv* env,
    jclass jcaller,
    jstring headerName,
    jstring headerValue) {
  return JNI_HttpUtil_IsAllowedHeader(env, base::android::JavaParamRef<jstring>(env, headerName),
      base::android::JavaParamRef<jstring>(env, headerValue));
}


}  // namespace net

#endif  // android_net_connectivity_org_chromium_net_HttpUtil_JNI
