// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


// This file is autogenerated by
//     third_party/jni_zero/jni_generator.py
// For
//     android/net/connectivity/org/chromium/net/X509Util

#ifndef android_net_connectivity_org_chromium_net_X509Util_JNI
#define android_net_connectivity_org_chromium_net_X509Util_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_helper.h"


// Step 1: Forward declarations.


// Step 2: Constants (optional).


// Step 3: Method stubs.
namespace net {

static void JNI_X509Util_NotifyClientCertStoreChanged(JNIEnv* env);

JNI_BOUNDARY_EXPORT void Java_android_net_connectivity_J_N_MYouFkpm(
    JNIEnv* env,
    jclass jcaller) {
  return JNI_X509Util_NotifyClientCertStoreChanged(env);
}

static void JNI_X509Util_NotifyTrustStoreChanged(JNIEnv* env);

JNI_BOUNDARY_EXPORT void Java_android_net_connectivity_J_N_MjPnG3OS(
    JNIEnv* env,
    jclass jcaller) {
  return JNI_X509Util_NotifyTrustStoreChanged(env);
}


}  // namespace net

#endif  // android_net_connectivity_org_chromium_net_X509Util_JNI
