// This file is autogenerated by hidl-gen. Do not edit manually.
// Source: android.hardware.wifi@1.0
// Location: hardware/interfaces/wifi/1.0/

package android.hardware.wifi.V1_0;

public class Constants {
    public final class NanParamSizeLimits {
        public static final int MIN_PASSPHRASE_LENGTH = 8;
        public static final int MAX_PASSPHRASE_LENGTH = 63;
    };

}
