// This file is autogenerated by hidl-gen. Do not edit manually.
// Source: android.hardware.usb@1.2
// Location: hardware/interfaces/usb/1.2/

package android.hardware.usb.V1_2;

public class Constants {
    public final class ContaminantDetectionStatus {
        public static final int NOT_SUPPORTED = 0;
        public static final int DISABLED = 1;
        public static final int NOT_DETECTED = 2;
        public static final int DETECTED = 3;
    };

    public final class ContaminantProtectionMode {
        public static final int NONE = 0;
        public static final int FORCE_SINK = 1 /* 1 << 0 */;
        public static final int FORCE_SOURCE = 2 /* 1 << 1 */;
        public static final int FORCE_DISABLE = 4 /* 1 << 2 */;
    };

    public final class ContaminantProtectionStatus {
        public static final int NONE = 0;
        public static final int FORCE_SINK = 1 /* 1 << 0 */;
        public static final int FORCE_SOURCE = 2 /* 1 << 1 */;
        public static final int FORCE_DISABLE = 4 /* 1 << 2 */;
        public static final int DISABLED = 8 /* 1 << 3 */;
    };

}
