// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     android.net.connectivity.org.chromium.base.ThreadUtils

#ifndef android_net_connectivity_org_chromium_base_ThreadUtils_JNI
#define android_net_connectivity_org_chromium_base_ThreadUtils_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_internal.h"

// Class Accessors
#ifndef android_net_connectivity_org_chromium_base_ThreadUtils_clazz_defined
#define android_net_connectivity_org_chromium_base_ThreadUtils_clazz_defined
inline jclass android_net_connectivity_org_chromium_base_ThreadUtils_clazz(JNIEnv* env) {
  static const char kClassName[] = "android.net.connectivity.org.chromium.base.ThreadUtils";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


// Native to Java functions
static jboolean Java_ThreadUtils_isThreadPriorityAudio(JNIEnv* env, JniIntWrapper tid) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_net_connectivity_org_chromium_base_ThreadUtils_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isThreadPriorityAudio",
      "(I)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), as_jint(tid));
  return _ret;
}

static void Java_ThreadUtils_setThreadPriorityAudio(JNIEnv* env, JniIntWrapper tid) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_net_connectivity_org_chromium_base_ThreadUtils_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "setThreadPriorityAudio",
      "(I)V",
      &cached_method_id);
  env->CallStaticVoidMethod(clazz, call_context.method_id(), as_jint(tid));
}



#endif  // android_net_connectivity_org_chromium_base_ThreadUtils_JNI
