/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.health.connect;

import static com.android.healthfitness.flags.Flags.FLAG_PERSONAL_HEALTH_RECORD;

import static java.util.Objects.requireNonNull;

import android.annotation.FlaggedApi;
import android.annotation.NonNull;

/** A class to represent filtering based on the identifier. */
@FlaggedApi(FLAG_PERSONAL_HEALTH_RECORD)
public final class MedicalIdFilter {
    @NonNull private final String mId;

    private MedicalIdFilter(@NonNull String id) {
        mId = id;
    }

    /**
     * Creates an instance of {@link MedicalIdFilter} based on an identifier generated by the
     * platform.
     */
    @NonNull
    public static MedicalIdFilter fromId(@NonNull String id) {
        requireNonNull(id);
        return new MedicalIdFilter(id);
    }

    /** Returns the identifier. */
    @NonNull
    public String getId() {
        return mId;
    }
}
