// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


// This file is autogenerated by
//     third_party/jni_zero/jni_generator.py
// For
//     android/net/connectivity/org/chromium/base/BundleUtils

#ifndef android_net_connectivity_org_chromium_base_BundleUtils_JNI
#define android_net_connectivity_org_chromium_base_BundleUtils_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_helper.h"


// Step 1: Forward declarations.

JNI_ZERO_COMPONENT_BUILD_EXPORT extern const char
    kClassPath_android_net_connectivity_org_chromium_base_BundleUtils[];
const char kClassPath_android_net_connectivity_org_chromium_base_BundleUtils[] =
    "android/net/connectivity/org/chromium/base/BundleUtils";
// Leaking this jclass as we cannot use LazyInstance from some threads.
JNI_ZERO_COMPONENT_BUILD_EXPORT std::atomic<jclass>
    g_android_net_connectivity_org_chromium_base_BundleUtils_clazz(nullptr);
#ifndef android_net_connectivity_org_chromium_base_BundleUtils_clazz_defined
#define android_net_connectivity_org_chromium_base_BundleUtils_clazz_defined
inline jclass android_net_connectivity_org_chromium_base_BundleUtils_clazz(JNIEnv* env) {
  return base::android::LazyGetClass(env,
      kClassPath_android_net_connectivity_org_chromium_base_BundleUtils,
      &g_android_net_connectivity_org_chromium_base_BundleUtils_clazz);
}
#endif


// Step 2: Constants (optional).


// Step 3: Method stubs.

static std::atomic<jmethodID>
    g_android_net_connectivity_org_chromium_base_BundleUtils_getNativeLibraryPath2(nullptr);
static base::android::ScopedJavaLocalRef<jstring> Java_BundleUtils_getNativeLibraryPath(JNIEnv* env,
    const base::android::JavaRef<jstring>& libraryName,
    const base::android::JavaRef<jstring>& splitName) {
  jclass clazz = android_net_connectivity_org_chromium_base_BundleUtils_clazz(env);
  CHECK_CLAZZ(env, clazz,
      android_net_connectivity_org_chromium_base_BundleUtils_clazz(env), nullptr);

  jni_generator::JniJavaCallContextChecked call_context;
  call_context.Init<
      base::android::MethodID::TYPE_STATIC>(
          env,
          clazz,
          "getNativeLibraryPath",
          "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
          &g_android_net_connectivity_org_chromium_base_BundleUtils_getNativeLibraryPath2);

  jstring ret =
      static_cast<jstring>(env->CallStaticObjectMethod(clazz,
          call_context.base.method_id, libraryName.obj(), splitName.obj()));
  return base::android::ScopedJavaLocalRef<jstring>(env, ret);
}

static std::atomic<jmethodID>
    g_android_net_connectivity_org_chromium_base_BundleUtils_isBundleForNative0(nullptr);
static jboolean Java_BundleUtils_isBundleForNative(JNIEnv* env) {
  jclass clazz = android_net_connectivity_org_chromium_base_BundleUtils_clazz(env);
  CHECK_CLAZZ(env, clazz,
      android_net_connectivity_org_chromium_base_BundleUtils_clazz(env), false);

  jni_generator::JniJavaCallContextChecked call_context;
  call_context.Init<
      base::android::MethodID::TYPE_STATIC>(
          env,
          clazz,
          "isBundleForNative",
          "()Z",
          &g_android_net_connectivity_org_chromium_base_BundleUtils_isBundleForNative0);

  jboolean ret =
      env->CallStaticBooleanMethod(clazz,
          call_context.base.method_id);
  return ret;
}

#endif  // android_net_connectivity_org_chromium_base_BundleUtils_JNI
