// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


// This file is autogenerated by
//     third_party/jni_zero/jni_generator.py
// For
//     android/net/connectivity/org/chromium/base/FieldTrialList

#ifndef android_net_connectivity_org_chromium_base_FieldTrialList_JNI
#define android_net_connectivity_org_chromium_base_FieldTrialList_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_helper.h"


// Step 1: Forward declarations.


// Step 2: Constants (optional).


// Step 3: Method stubs.
static jboolean JNI_FieldTrialList_CreateFieldTrial(JNIEnv* env, const
    base::android::JavaParamRef<jstring>& trialName,
    const base::android::JavaParamRef<jstring>& groupName);

JNI_BOUNDARY_EXPORT jboolean Java_android_net_connectivity_J_N_MeuypufV(
    JNIEnv* env,
    jclass jcaller,
    jstring trialName,
    jstring groupName) {
  return JNI_FieldTrialList_CreateFieldTrial(env, base::android::JavaParamRef<jstring>(env,
      trialName), base::android::JavaParamRef<jstring>(env, groupName));
}

static base::android::ScopedJavaLocalRef<jstring> JNI_FieldTrialList_FindFullName(JNIEnv* env, const
    base::android::JavaParamRef<jstring>& trialName);

JNI_BOUNDARY_EXPORT jstring Java_android_net_connectivity_J_N_MlRxL19I(
    JNIEnv* env,
    jclass jcaller,
    jstring trialName) {
  return JNI_FieldTrialList_FindFullName(env, base::android::JavaParamRef<jstring>(env,
      trialName)).Release();
}

static base::android::ScopedJavaLocalRef<jstring> JNI_FieldTrialList_GetVariationParameter(JNIEnv*
    env, const base::android::JavaParamRef<jstring>& trialName,
    const base::android::JavaParamRef<jstring>& parameterKey);

JNI_BOUNDARY_EXPORT jstring Java_android_net_connectivity_J_N_MR6yK_1wY(
    JNIEnv* env,
    jclass jcaller,
    jstring trialName,
    jstring parameterKey) {
  return JNI_FieldTrialList_GetVariationParameter(env, base::android::JavaParamRef<jstring>(env,
      trialName), base::android::JavaParamRef<jstring>(env, parameterKey)).Release();
}

static void JNI_FieldTrialList_LogActiveTrials(JNIEnv* env);

JNI_BOUNDARY_EXPORT void Java_android_net_connectivity_J_N_Mxmj6HmS(
    JNIEnv* env,
    jclass jcaller) {
  return JNI_FieldTrialList_LogActiveTrials(env);
}

static jboolean JNI_FieldTrialList_TrialExists(JNIEnv* env, const
    base::android::JavaParamRef<jstring>& trialName);

JNI_BOUNDARY_EXPORT jboolean Java_android_net_connectivity_J_N_MQvsrB2i(
    JNIEnv* env,
    jclass jcaller,
    jstring trialName) {
  return JNI_FieldTrialList_TrialExists(env, base::android::JavaParamRef<jstring>(env, trialName));
}


#endif  // android_net_connectivity_org_chromium_base_FieldTrialList_JNI
