// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


// This file is autogenerated by
//     third_party/jni_zero/jni_generator.py
// For
//     android/net/connectivity/org/chromium/base/RadioUtils

#ifndef android_net_connectivity_org_chromium_base_RadioUtils_JNI
#define android_net_connectivity_org_chromium_base_RadioUtils_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_helper.h"


// Step 1: Forward declarations.

JNI_ZERO_COMPONENT_BUILD_EXPORT extern const char
    kClassPath_android_net_connectivity_org_chromium_base_RadioUtils[];
const char kClassPath_android_net_connectivity_org_chromium_base_RadioUtils[] =
    "android/net/connectivity/org/chromium/base/RadioUtils";
// Leaking this jclass as we cannot use LazyInstance from some threads.
JNI_ZERO_COMPONENT_BUILD_EXPORT std::atomic<jclass>
    g_android_net_connectivity_org_chromium_base_RadioUtils_clazz(nullptr);
#ifndef android_net_connectivity_org_chromium_base_RadioUtils_clazz_defined
#define android_net_connectivity_org_chromium_base_RadioUtils_clazz_defined
inline jclass android_net_connectivity_org_chromium_base_RadioUtils_clazz(JNIEnv* env) {
  return base::android::LazyGetClass(env,
      kClassPath_android_net_connectivity_org_chromium_base_RadioUtils,
      &g_android_net_connectivity_org_chromium_base_RadioUtils_clazz);
}
#endif


// Step 2: Constants (optional).


// Step 3: Method stubs.
namespace base {
namespace android {


static std::atomic<jmethodID>
    g_android_net_connectivity_org_chromium_base_RadioUtils_getCellDataActivity0(nullptr);
static jint Java_RadioUtils_getCellDataActivity(JNIEnv* env) {
  jclass clazz = android_net_connectivity_org_chromium_base_RadioUtils_clazz(env);
  CHECK_CLAZZ(env, clazz,
      android_net_connectivity_org_chromium_base_RadioUtils_clazz(env), 0);

  jni_generator::JniJavaCallContextChecked call_context;
  call_context.Init<
      base::android::MethodID::TYPE_STATIC>(
          env,
          clazz,
          "getCellDataActivity",
          "()I",
          &g_android_net_connectivity_org_chromium_base_RadioUtils_getCellDataActivity0);

  jint ret =
      env->CallStaticIntMethod(clazz,
          call_context.base.method_id);
  return ret;
}

static std::atomic<jmethodID>
    g_android_net_connectivity_org_chromium_base_RadioUtils_getCellSignalLevel0(nullptr);
static jint Java_RadioUtils_getCellSignalLevel(JNIEnv* env) {
  jclass clazz = android_net_connectivity_org_chromium_base_RadioUtils_clazz(env);
  CHECK_CLAZZ(env, clazz,
      android_net_connectivity_org_chromium_base_RadioUtils_clazz(env), 0);

  jni_generator::JniJavaCallContextChecked call_context;
  call_context.Init<
      base::android::MethodID::TYPE_STATIC>(
          env,
          clazz,
          "getCellSignalLevel",
          "()I",
          &g_android_net_connectivity_org_chromium_base_RadioUtils_getCellSignalLevel0);

  jint ret =
      env->CallStaticIntMethod(clazz,
          call_context.base.method_id);
  return ret;
}

static std::atomic<jmethodID>
    g_android_net_connectivity_org_chromium_base_RadioUtils_isSupported0(nullptr);
static jboolean Java_RadioUtils_isSupported(JNIEnv* env) {
  jclass clazz = android_net_connectivity_org_chromium_base_RadioUtils_clazz(env);
  CHECK_CLAZZ(env, clazz,
      android_net_connectivity_org_chromium_base_RadioUtils_clazz(env), false);

  jni_generator::JniJavaCallContextChecked call_context;
  call_context.Init<
      base::android::MethodID::TYPE_STATIC>(
          env,
          clazz,
          "isSupported",
          "()Z",
          &g_android_net_connectivity_org_chromium_base_RadioUtils_isSupported0);

  jboolean ret =
      env->CallStaticBooleanMethod(clazz,
          call_context.base.method_id);
  return ret;
}

static std::atomic<jmethodID>
    g_android_net_connectivity_org_chromium_base_RadioUtils_isWifiConnected0(nullptr);
static jboolean Java_RadioUtils_isWifiConnected(JNIEnv* env) {
  jclass clazz = android_net_connectivity_org_chromium_base_RadioUtils_clazz(env);
  CHECK_CLAZZ(env, clazz,
      android_net_connectivity_org_chromium_base_RadioUtils_clazz(env), false);

  jni_generator::JniJavaCallContextChecked call_context;
  call_context.Init<
      base::android::MethodID::TYPE_STATIC>(
          env,
          clazz,
          "isWifiConnected",
          "()Z",
          &g_android_net_connectivity_org_chromium_base_RadioUtils_isWifiConnected0);

  jboolean ret =
      env->CallStaticBooleanMethod(clazz,
          call_context.base.method_id);
  return ret;
}

}  // namespace android
}  // namespace base

#endif  // android_net_connectivity_org_chromium_base_RadioUtils_JNI
