// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


// This file is autogenerated by
//     third_party/jni_zero/jni_generator.py
// For
//     android/net/connectivity/org/chromium/base/ThreadUtils

#ifndef android_net_connectivity_org_chromium_base_ThreadUtils_JNI
#define android_net_connectivity_org_chromium_base_ThreadUtils_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "third_party/jni_zero/jni_zero_helper.h"


// Step 1: Forward declarations.

JNI_ZERO_COMPONENT_BUILD_EXPORT extern const char
    kClassPath_android_net_connectivity_org_chromium_base_ThreadUtils[];
const char kClassPath_android_net_connectivity_org_chromium_base_ThreadUtils[] =
    "android/net/connectivity/org/chromium/base/ThreadUtils";
// Leaking this jclass as we cannot use LazyInstance from some threads.
JNI_ZERO_COMPONENT_BUILD_EXPORT std::atomic<jclass>
    g_android_net_connectivity_org_chromium_base_ThreadUtils_clazz(nullptr);
#ifndef android_net_connectivity_org_chromium_base_ThreadUtils_clazz_defined
#define android_net_connectivity_org_chromium_base_ThreadUtils_clazz_defined
inline jclass android_net_connectivity_org_chromium_base_ThreadUtils_clazz(JNIEnv* env) {
  return base::android::LazyGetClass(env,
      kClassPath_android_net_connectivity_org_chromium_base_ThreadUtils,
      &g_android_net_connectivity_org_chromium_base_ThreadUtils_clazz);
}
#endif


// Step 2: Constants (optional).


// Step 3: Method stubs.

static std::atomic<jmethodID>
    g_android_net_connectivity_org_chromium_base_ThreadUtils_isThreadPriorityAudio1(nullptr);
static jboolean Java_ThreadUtils_isThreadPriorityAudio(JNIEnv* env, JniIntWrapper tid) {
  jclass clazz = android_net_connectivity_org_chromium_base_ThreadUtils_clazz(env);
  CHECK_CLAZZ(env, clazz,
      android_net_connectivity_org_chromium_base_ThreadUtils_clazz(env), false);

  jni_generator::JniJavaCallContextChecked call_context;
  call_context.Init<
      base::android::MethodID::TYPE_STATIC>(
          env,
          clazz,
          "isThreadPriorityAudio",
          "(I)Z",
          &g_android_net_connectivity_org_chromium_base_ThreadUtils_isThreadPriorityAudio1);

  jboolean ret =
      env->CallStaticBooleanMethod(clazz,
          call_context.base.method_id, as_jint(tid));
  return ret;
}

static std::atomic<jmethodID>
    g_android_net_connectivity_org_chromium_base_ThreadUtils_setThreadPriorityAudio1(nullptr);
static void Java_ThreadUtils_setThreadPriorityAudio(JNIEnv* env, JniIntWrapper tid) {
  jclass clazz = android_net_connectivity_org_chromium_base_ThreadUtils_clazz(env);
  CHECK_CLAZZ(env, clazz,
      android_net_connectivity_org_chromium_base_ThreadUtils_clazz(env));

  jni_generator::JniJavaCallContextChecked call_context;
  call_context.Init<
      base::android::MethodID::TYPE_STATIC>(
          env,
          clazz,
          "setThreadPriorityAudio",
          "(I)V",
          &g_android_net_connectivity_org_chromium_base_ThreadUtils_setThreadPriorityAudio1);

     env->CallStaticVoidMethod(clazz,
          call_context.base.method_id, as_jint(tid));
}

#endif  // android_net_connectivity_org_chromium_base_ThreadUtils_JNI
